### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 22516

### ISSUE THREAD

**Issue by quoidautre** [thewhiteh4t/nexfil#13]
Hi,
When I launch your script, I've this error. I'm on Windows 10, and I'm using pipenv.

```
(nexfil-HrktdyP2) λ python nexfil.py -u snowden
[+] Importing Modules...

[+] Checking Connectivity...

__   _ _____ _     _ _____ _____ _
| \  | |____  \___/  |____   |   |
|  \_| |____ _/   \_ |     __|__ |_____

[>] Created By : thewhiteh4t
 |---> Twitter : https://twitter.com/thewhiteh4t
 |---> Discord : https://discord.gg/UM92zUn
[>] Version    : 1.0.0

[!] Loading URLs...
Traceback (most recent call last):
  File "nexfil.py", line 369, in <module>
    raw_data = url_store.read()
  File "c:\users\me\appdata\local\programs\python\python38\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 22516: character maps to <undefined>
```

Thanks,
Have a nice day

F.

**Comment by gadcam** [comment]
Hi @quoidautre,
This PR should address the issue #15.

**Comment by gadcam** [comment]
Note that you may also need #16.

**Comment by Beldramma** [comment]
Hi @gadcam,
Thanks for your modifications, i have added issue  #15 and #16, and it seems to work.
I say "seem", because for the "adam" username example I have only 10 possible profiles, and in the README we can see 247 possible profiles. I have also tested the script for some known usernames, but I have no possible profiles returned, or there should be possible profiles.

**Comment by thewhiteh4t** [comment]
@Beldramma are you using proxy/vpn/tor ?
